INSERT INTO player_data (name) VALUES ('Maria Sharapova');
INSERT INTO player_data (name) VALUES ('Anna Kournikova');
INSERT INTO player_data (name) VALUES ('Svetlana Kuznetsova');
INSERT INTO player_data (name) VALUES ('Ekaterina Alexandrova');
INSERT INTO player_data (name) VALUES ('Anastasia Pavlyuchenkova');
INSERT INTO player_data (name) VALUES ('Veronika Kudermetova');
INSERT INTO player_data (name) VALUES ('Elena Dementieva');
INSERT INTO player_data (name) VALUES ('Daria Kasatkina');

INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (1, 2, 1);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (2, 1, 2);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (2, 3, 2);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (3, 2, 3);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (3, 4, 3);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (4, 3, 4);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (4, 5, 4);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (5, 4, 5);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (5, 6, 5);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (6, 5, 6);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (6, 7, 6);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (7, 6, 7);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (7, 8, 7);
INSERT INTO match_data (player_one_id, player_two_id, winner_id) VALUES (8, 7, 8);
